---
title: "Reponses TP4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exercice n°1

### Question a

```{r}
echantillon <- rnorm(30, 10, 2) #Echantillon de taille 30, esperence 10 et var 4 (écart type 2)
```

### Question b

```{r}
xbar = mean(echantillon) #Moyenne observée
xbar

S2 <- sum((echantillon-xbar)**2 )/30 #Variance observée (sommme echantillon - moyenne au carré, divisé par cardinal)
S2

Sc2 <- sum((echantillon-xbar)**2 )/29 #Variance variance corrigée
Sc2
```

### Question c

```{r}
#Borne inférieure de l'intervale de confiance de la moyenne (à 10% : 0.1)
BI = xbar + sqrt(Sc2)*qt(0.1/2, 29)/sqrt(30)
BS = xbar + sqrt(Sc2)*qt(1-0.1/2, 29)/sqrt(30)
```

### Question d

```{r}
#Borne inférieure de l'intervale de confiance de la variance (à 10% : 0.1)
BI <- 29*var(echantillon)/qchisq(1-0.1/2, 29)
BS = 29*var(echantillon)/qchisq(0.1, 29)
```

## Exercice 2

### Question a
```{r}
masses.cp <- as.numeric(unlist(strsplit("0.81 0.84 0.83 0.80 0.85 0.86 0.85 0.83 0.84 0.80", split = " ")))
mean(masses.cp)
```
On cherche à tester si l'espérence est bien de 0.83. Pour cela, il convient de regarder un intervale de confiance significatif (95% typiquement) et de vérifier si la moyenne observée rentre dedans.

### Question b
```{r}

```
